apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
  type: ClusterIP
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "16686"
spec:
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 32100
  selector:
    app: jaeger
  type: NodePort
