apiVersion: v1
kind: Service
metadata:
  name: postgres-restaurant
  labels:
    app: postgres-restaurant
spec:
  ports:
    - port: 5432
      name: postgres-restaurant
  clusterIP: None
  selector:
    app: postgres-restaurant
