apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8024"
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
  selector:
    app: axonserver
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  ports:
    - name: grpc
      port: 8124
      targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver
